import { defHttp } from '@/utils/http/axios';
import { ErrorMessageMode } from '#/axios';

const URL_PREFIX = '/menu/';

export const MenuAPI = {
  init() {
    return {
      id: 0,
      appId: null,
      code: null,
      name: null,
      module: null,
      url: null,
      type: null,
      parentId: null,
      icon: null,
      parentFlag: null,
      displayFlag: null,
      sort: null,
    };
  },

  getMenu(params = {}, errorMessageMode: ErrorMessageMode = 'modal') {
    return defHttp.post({ url: URL_PREFIX + 'getMenu', params }, { errorMessageMode });
  },

  listMenu(params = {}, errorMessageMode: ErrorMessageMode = 'none') {
    return defHttp.post({ url: URL_PREFIX + 'listMenu', params }, { errorMessageMode });
  },

  insertMenu(params = {}, errorMessageMode: ErrorMessageMode = 'modal') {
    return defHttp.post(
      { url: URL_PREFIX + 'insertMenu', params: { data: JSON.stringify(params) } },
      { errorMessageMode },
    );
  },

  updateMenu(params = {}, errorMessageMode: ErrorMessageMode = 'modal') {
    return defHttp.post(
      { url: URL_PREFIX + 'updateMenu', params: { data: JSON.stringify(params) } },
      { errorMessageMode },
    );
  },

  deleteMenu(params = {}, errorMessageMode: ErrorMessageMode = 'modal') {
    return defHttp.post({ url: URL_PREFIX + 'deleteMenu', params }, { errorMessageMode });
  },

  listMenuWithOperationByUserId(params = {}, errorMessageMode: ErrorMessageMode = 'modal') {
    // return defHttp.post(
    //   { url: URL_PREFIX + 'listMenuWithOperationByUserId', params },
    //   { errorMessageMode },
    // );

    return {
      allMenu: [
        {
          id: 1,
          code: 'dashboard',
          name: '数据看板',
          url: '/dashboard',
          icon: 'fa fa-address-book-o',
          parentId: 0,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [
            {
              id: 5,
              code: 'delete',
              name: '删除',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 4,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 2,
              code: 'insert',
              name: '添加',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 1,
              code: 'list',
              name: '查询',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
          ],
          dataRuleList: null,
        },
        {
          id: 2,
          code: 'analysis',
          name: '数据分析',
          url: '/dashboard/analysis',
          icon: 'fa fa-address-book-o',
          parentId: 1,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [
            {
              id: 5,
              code: 'delete',
              name: '删除',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 4,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 2,
              code: 'insert',
              name: '添加',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 1,
              code: 'list',
              name: '查询',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
          ],
          dataRuleList: null,
        },
        {
          id: 3,
          code: 'workbench',
          name: '工作台',
          url: '/dashboard/workbench',
          icon: 'fa fa-address-book-o',
          parentId: 1,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [
            {
              id: 5,
              code: 'delete',
              name: '删除',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 4,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 2,
              code: 'insert',
              name: '添加',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 1,
              code: 'list',
              name: '查询',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
          ],
          dataRuleList: null,
        },
        {
          id: 4,
          code: 'auth',
          name: '权限管理',
          url: '/permission',
          icon: 'fa fa-address-card',
          parentId: 0,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [],
          dataRuleList: null,
        },
        {
          id: 5,
          code: 'app',
          name: '应用管理',
          url: '/permission/app',
          icon: 'fa fa-address-book-o',
          parentId: 4,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [
            {
              id: 5,
              code: 'delete',
              name: '删除',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 4,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 2,
              code: 'insert',
              name: '添加',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 1,
              code: 'list',
              name: '查询',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
          ],
          dataRuleList: null,
        },
        {
          id: 6,
          code: 'user-info',
          name: '个人信息设置',
          url: '/permission/user-info',
          icon: 'fa fa-trophy',
          parentId: 4,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [
            {
              id: 5,
              code: 'delete',
              name: '删除',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 4,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 2,
              code: 'insert',
              name: '添加',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 1,
              code: 'list',
              name: '查询',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
          ],
          dataRuleList: null,
        },
        {
          id: 7,
          code: 'menu',
          name: '功能管理',
          url: '/permission/menu',
          icon: 'fa fa-object-ungroup',
          parentId: 4,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [
            {
              id: 50,
              code: 'copy',
              name: '复制',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 4,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 54,
              code: 'delete-child',
              name: '删除子菜单',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 2,
              code: 'insert',
              name: '添加',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 52,
              code: 'update-child',
              name: '修改子菜单',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 1,
              code: 'list',
              name: '查询',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 53,
              code: 'insert-child',
              name: '新增子菜单',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 5,
              code: 'delete',
              name: '删除',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
          ],
          dataRuleList: null,
        },
        {
          id: 8,
          code: 'user',
          name: '用户管理',
          url: '/permission/user',
          icon: 'fa fa-bank',
          parentId: 4,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [
            {
              id: 5,
              code: 'delete',
              name: '删除',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 4,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 2,
              code: 'insert',
              name: '添加',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 1,
              code: 'list',
              name: '查询',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 58,
              code: 'reset-password',
              name: '重置密码',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 223,
              code: 'update-password',
              name: '修改密码',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
          ],
          dataRuleList: null,
        },
        {
          id: 9,
          code: 'role',
          name: '角色管理',
          url: '/permission/role',
          icon: 'fa fa-arrows',
          parentId: 4,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [
            {
              id: 57,
              code: 'save-menu',
              name: '保存修改按钮',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 1,
              code: 'list',
              name: '查询',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 55,
              code: 'update-menu',
              name: '修改菜单权限',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 4,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 2,
              code: 'insert',
              name: '添加',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 56,
              code: 'cancel-menu',
              name: '取消修改按钮',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 5,
              code: 'delete',
              name: '删除',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
          ],
          dataRuleList: null,
        },
        {
          id: 10,
          code: 'role-menu-operation',
          name: '功能权限(角色)',
          url: '/permission/role-menu-operation',
          icon: 'fa fa-arrows',
          parentId: 4,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [
            {
              id: 5,
              code: 'delete',
              name: '删除',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 64,
              code: 'update-data',
              name: '修改数据按钮',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 65,
              code: 'delete-data',
              name: '删除数据按钮',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 4,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 63,
              code: 'insert-data',
              name: '数据新增按钮',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 2,
              code: 'insert',
              name: '添加',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 66,
              code: 'update-button',
              name: '更新按钮权限',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 1,
              code: 'list',
              name: '查询',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 62,
              code: 'refresh',
              name: '刷新权限',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
          ],
          dataRuleList: null,
        },
        {
          id: 11,
          code: 'user-menu-operation',
          name: '功能权限(用户)',
          url: '/permission/user-menu-operation',
          icon: 'fa fa-arrows',
          parentId: 4,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [
            {
              id: 5,
              code: 'delete',
              name: '删除',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 4,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 2,
              code: 'insert',
              name: '添加',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 1,
              code: 'list',
              name: '查询',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
          ],
          dataRuleList: null,
        },
        {
          id: 12,
          code: 'menu-operation',
          name: '功能权限',
          url: '/permission/menu-operation',
          icon: 'fa fa-bars',
          parentId: 4,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [
            {
              id: 4,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 2,
              code: 'insert',
              name: '添加',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 1,
              code: 'list',
              name: '查询',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 5,
              code: 'delete',
              name: '删除',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
          ],
          dataRuleList: null,
        },
        {
          id: 13,
          code: 'dict',
          name: '字典管理',
          url: '/permission/dict',
          icon: 'fa fa-bars',
          parentId: 4,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [
            {
              id: 4,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 2,
              code: 'insert',
              name: '添加',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 1,
              code: 'list',
              name: '查询',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 5,
              code: 'delete',
              name: '删除',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
          ],
          dataRuleList: null,
        },
        {
          id: 14,
          code: 'coding-rule',
          name: '编码规则',
          url: '/permission/coding-rule',
          icon: 'fa fa-bars',
          parentId: 4,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [
            {
              id: 5,
              code: 'delete',
              name: '删除',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 4,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 2,
              code: 'insert',
              name: '添加',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 1,
              code: 'list',
              name: '查询',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
          ],
          dataRuleList: null,
        },

        {
          id: 15,
          code: 'organize',
          name: '组织架构',
          url: '/permission/organize',
          icon: 'fa fa-group',
          parentId: 4,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [
            {
              id: 4,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 122,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 1,
              code: 'list',
              name: '查询',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 121,
              code: 'save',
              name: '保存',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 5,
              code: 'delete',
              name: '删除',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 123,
              code: 'cancel',
              name: '取消',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 2,
              code: 'insert',
              name: '添加',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
          ],
          dataRuleList: null,
        },
        {
          id: 16,
          code: 'system-params',
          name: '系统参数',
          url: '/permission/system-params',
          icon: 'fa fa-cog',
          parentId: 4,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [
            {
              id: 4,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 5,
              code: 'delete',
              name: '删除',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 2,
              code: 'insert',
              name: '添加',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
          ],
          dataRuleList: null,
        },
        {
          id: 17,
          code: 'customer-info',
          name: '客户信息配置',
          url: '/permission/customer-info',
          icon: 'fa fa-check',
          parentId: 4,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [
            {
              id: 2,
              code: 'insert',
              name: '添加',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 4,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 5,
              code: 'delete',
              name: '删除',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
          ],
          dataRuleList: null,
        },
        {
          id: 18,
          code: 'log-module',
          name: '日志管理',
          url: '/log-module',
          icon: 'fa fa-suitcase',
          parentId: 0,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [],
          dataRuleList: null,
        },
        {
          id: 19,
          code: 'permission-log',
          name: '系统权限日志',
          url: '/log/permission-log',
          icon: 'fa fa-align-justify',
          parentId: 18,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [
            {
              id: 5,
              code: 'delete',
              name: '删除',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 2,
              code: 'insert',
              name: '添加',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 1,
              code: 'list',
              name: '查询',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 4,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
          ],
          dataRuleList: null,
        },
        {
          id: 20,
          code: 'operate-log',
          name: '系统操作日志',
          url: '/log/operate-log',
          icon: 'fa fa-flag',
          parentId: 18,
          operationId: null,
          parentFlag: true,
          operationCoce: null,
          operationName: null,
          displayFlag: true,
          operationList: [
            {
              id: 5,
              code: 'delete',
              name: '删除',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 2,
              code: 'insert',
              name: '添加',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 4,
              code: 'update',
              name: '修改',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
            {
              id: 1,
              code: 'list',
              name: '查询',
              menuId: null,
              icon: null,
              deleteFlag: null,
            },
          ],
          dataRuleList: null,
        },
      ],
    };
  },
};
